# **Tarea de Numpy**

Este notebook es el de los ejercicios >:)

In [2]:
#!pip install numpy
import numpy as np

# Probando si si jala el numpy
my_arreglow = np.array([1, 2, 3, 4, 5])

print(my_arreglow)
print(np.mean(my_arreglow))


[1 2 3 4 5]
3.0


## Ejercicios de refuerzo

### **Ejercicio 1 - Crear un array de ceros:**
Crea un array de tamaño (3, 4) lleno de ceros.

In [31]:
# Solución (:
arr_ceros = np.zeros((3, 4))
print(arr_ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### **Ejercicio 2-  Suma de elementos:**
   Dado el array [1, 2, 3, 4, 5], calcula la suma de todos sus elementos usando NumPy.

In [5]:
# Solucion :)
numeros = np.array([1, 2, 3, 4, 5])
suma = np.sum(numeros)
print(suma)

15


### **Ejercicio 3 - Encontrar el máximo y mínimo:**
Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.

In [9]:
# Solución:)
array = np.array([10, 20, 30, 40, 50])

maximo = np.max(array)
print("El valor max es: ", maximo)
minimo = np.min(array)
print("El valor min es:", minimo)

El valor max es:  50
El valor min es: 10


### **Ejercicio 4 - Encontrar el máximo y mínimo:**
 Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.


In [10]:
# Solución:)
array = np.array([10, 20, 30, 40, 50])

maximo = np.max(array)
print("El valor max es: ", maximo)
minimo = np.min(array)
print("El valor min es:", minimo)

El valor max es:  50
El valor min es: 10


### **Ejercicio 5 - Generar números aleatorios:**
  Genera un array de 5 números aleatorios entre 0 y 1.

In [42]:
# Solución:)
num_aleatorios = np.random.randint(0, 100, size=(1, 5))
num_aleatorios = num_aleatorios / 100
print(num_aleatorios)

[[0.6  0.7  0.87 0.61 0.93]]


### **Ejercicio 6 - Promedio de un array:**
Dado el array [5, 10, 15, 20, 25], calcula su promedio usando NumPy.

In [43]:
#Solucion:)
arr_ej6 = np.array([5, 10, 15, 20, 25])
promedio = np.mean(arr_ej6)
print("El promedio es:", promedio)

El promedio es: 15.0


### **Ejercicio 7 - Concatenar dos arrays**
Dados los arrays A = [1, 2, 3] y B = [4, 5, 6], concaténalos en un solo array.

In [51]:
#Solucion:)
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
#Contatenando los arrays
C = np.concatenate((A, B))
print(C)

[1 2 3 4 5 6]


### **Ejercicio 8 - Reshape de un Array**
Dado el array [1, 2, 3, 4, 5, 6], cámbialo a una matriz de 2x3.

In [64]:
#Solución:)
arr_ej8 = np.array([1, 2, 3, 4, 5, 6])
arr_2x3 = arr_ej8.reshape(2, 3)
print(arr_2x3)

[[1 2 3]
 [4 5 6]]


### **Ejercicio 9 - Producto punto (dot product):**
Dados dos arrays A = [1, 2, 3] y B = [4, 5, 6], calcula su producto punto

In [66]:
#Solución:)
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print("Producto punto:", np.dot(A, B))

Producto punto: 32


### **Ejercicio 10 - Reorganizar un array:**
Dado el array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], conviértelo en una matriz (2, 5).

In [67]:
#Solución:)
arr_ej10 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr_2x5 = arr_ej10.reshape(2, 5)
print(arr_2x5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### **Ejercicio extra - Encontrar el *k*-ésimo elemento más pequeño en un array**
Dado arr = np.array([9, 3, 6, 2, 1, 7]), encuentra el 3er elemento más pequeño sin ordenar el array completo.

**Pista solución 1**: Se puede hacer con un método de Numpy

**Pista solución 2**: El código se hace más complicado, pero se puede resolver con ciclos iterativos.

In [80]:
#Solucion :o
arr = np.array([9, 3, 6, 2, 1, 7])
# np.partition ordena el array de tal forma que el tercer mínimo queda en la posición 2
# y los demás elementos quedan en cualquier orden
# El tercer mínimo es el elemento en la posición [2]
min3 = np.partition(arr, 2)[2]
print("El tercer mínimo es:", min3)


El tercer mínimo es: 3


## **Ejercicios aplicados**

### **Ejercicio: Cálculo de ROI (Retorno de Inversión)**
Dadas las inversiones ([1000, 1500, 2000]) y sus retornos ([1200, 1650, 1800]), calcula el ROI porcentual para cada caso.

*(Fórmula: ROI = (retorno - inversión) / inversión * 100)*

In [88]:
# Solucion del ROIROIROIROIORIORI
inversiones = np.array([1000, 1500, 2000])
retornos = np.array([1200, 1650, 1800])

roi = (retornos - inversiones) / inversiones * 100
print("El ROI es", roi)

El ROI es [ 20.  10. -10.]


### **Ejercicio: Normalización de Datos**
Tienes un dataset de precios de productos (en USD): [250, 320, 150, 500, 210]. Normaliza los valores al rango [0, 1] para compararlos en una escala común.

**Formulita de la normalización**: (x - min) / (max - min): Para una escala valores entre 0 y 1.

In [87]:
productos = np.array([250, 320, 150, 500, 210])

normalizados = (productos - np.min(productos)) / (np.max(productos) - np.min(productos))
print("Valores normalizados", normalizados)


Valores normalizados [0.28571429 0.48571429 0.         1.         0.17142857]


### **Ejercicio: Filtrado de Datos**
En un array de ventas diarias ([1200, 0, 750, 2400, 0, 1800]), reemplaza los ceros (días sin ventas) por el promedio de los días con ventas.

In [96]:
ventas_diarias = np.array([1200, 0, 750, 2400, 0, 1800])
promedio_ventas = np.mean(ventas_diarias[ventas_diarias != 0])
print("Promedio de ventas diarias:", promedio_ventas)

ventas_diarias[ventas_diarias == 0] = promedio_ventas
print("Ventas sin ceros: ", ventas_diarias)



Promedio de ventas diarias: 1537.5
Ventas sin ceros:  [1200 1537  750 2400 1537 1800]


### **Ejercicio - Análisis de Presión Arterial**
Tenemos un dataset de mediciones de presión arterial sistólica (mmHg) de 10 pacientes:
[120, 135, 140, 118, 150, 130, 160, 125, 142, 128].

Calculen:
- Media y desviación estándar.
- Identifiquen valores fuera del rango normal (90–140 mmHg).

In [98]:
presion = np.array([120, 135, 140, 118, 150, 130, 160, 125, 142, 128])

media = np.mean(presion)
desviacion = np.std(presion)

valores_atipicos = presion[(presion < 90) | (presion > 140)]

print("El promedio es:", media)
print("La desviación estándar es:", desviacion)
print("Valores atípicos:", valores_atipicos)

El promedio es: 134.8
La desviación estándar es: 12.69488085804668
Valores atípicos: [150 160 142]


### **Ejercicio - Cálculo del PIB per Cápita**
Dados el PIB (en millones de USD) [500, 320, 700, 450] y la población (en millones) [10, 8, 12, 9] de 4 países, calculen el PIB per cápita y determinen el país con el mayor valor.

In [106]:
pib = np.array([500, 320, 700, 450])
poblacion = np.array([10, 8, 12, 9])
pib_per_capita = pib / poblacion
print("PIB per cápita:", pib_per_capita)

pais_maximo = np.argmax(pib_per_capita)
print("El país con el PIB per cápita más alto es:", pais_maximo)

PIB per cápita: [50.         40.         58.33333333 50.        ]
El país con el PIB per cápita más alto es: 2


### **Ejercicio - Sistema de Drops (Probabilidades)**
En un videojuego RPG, los enemigos al ser vencidos, pueden dropear (soltar):
- 0 = Nada (50%).
- 1 = Poción (30%).
- 2 = Arma (15%).
- 3 = Artefacto (5%).

Simula 100 drops y cuenta cuántos artefactos se obtuvieron.

*Ejemplo de salida*:

```
Artifactos obtenidos: 3
```



In [121]:
# Solución usando np.random.choice
drops_probabilidad = np.array([0.50, 0.30, 0.15, 0.05])

#np.random.choice genera un array de 100 elementos aleatorios
# donde cada elemento es un drop entre 0 y 3, con probabilidades dadas por drops_probabilidad
simulacion = np.random.choice([0, 1, 2, 3], size = 100, p = drops_probabilidad)

# np.sum cuenta cuántos elementos son iguales al drop 3
total_artefactos = np.sum(simulacion == 3)
print("Total de artefactos:", total_artefactos)

Total de artefactos: 11
